/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login_register;

import java.awt.Color;
import java.awt.Frame;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.border.Border;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class lOGINFORM extends javax.swing.JFrame {

    /**
     * Creates new form lOGINFORM
     */
    public lOGINFORM() {
        initComponents();
        //CENTER THE FORM 
        
        /* - Download the connector  fpr HAVA & Mysql database*/ 
        /*Open xampp and start apache & mysql*/
        // * Go to  localhost/phpmyadmin*/
        //** Create a connection with the db /
        
        this.setLocationRelativeTo(null);
        
        //edited by kipa 
        
        // create a black boarder for the jpanel_title
        //0 border in the top
        Border jpanel_title_border = BorderFactory.createMatteBorder(0,1,1,1,Color.yellow);
         jpanel_title.setBorder(jpanel_title_border);
         
                  // create an orange border for the global panel 
          Border glob_panel_border = BorderFactory.createMatteBorder(1,1,1,1,Color.orange); 
          jPanel1.setBorder(glob_panel_border);
         
         // create a black border for the close  & minimize jlabels 
          Border label_border = BorderFactory.createMatteBorder(1,1,1,1,Color.black); 
          jLabel_min.setBorder(label_border);
          jLabel_close.setBorder(label_border);
          
          // create a border for the create account jlabel 
          Border label_Create_Account_border = BorderFactory.createMatteBorder(0,0,1,0,  Color.lightGray); 
          jLabel_Create_Account.setBorder(label_Create_Account_border);
          
          //create a border with the colr of the parent jpanel for the icon laebl to remove the move
          
           Border label_icons_border = BorderFactory.createMatteBorder(1,1,1,1, new Color (152,153,153)); 
          jLabel_username.setBorder(label_icons_border);
          jLabel_password.setBorder(label_icons_border);
          
          //create border for the username and password field
          Border field_border = BorderFactory.createMatteBorder(1,5,1,1, Color.white ); 
          jTextField_username.setBorder(field_border);
          jPasswordField.setBorder(field_border);
          
          
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lab = new javax.swing.JPanel();
        jLabel_min = new javax.swing.JLabel();
        jLabel_close = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel_username = new javax.swing.JLabel();
        jLabel_password = new javax.swing.JLabel();
        jTextField_username = new javax.swing.JTextField();
        jPasswordField = new javax.swing.JPasswordField();
        jButton_login = new javax.swing.JButton();
        jLabel_Create_Account = new javax.swing.JLabel();
        jpanel_title = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 51));

        lab.setBackground(new java.awt.Color(153, 153, 153));

        jLabel_min.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_min.setText("  -");
        jLabel_min.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_minMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_minMouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_minMouseClicked(evt);
            }
        });

        jLabel_close.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel_close.setText("  X");
        jLabel_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseClicked(evt);
            }
        });

        jLabel_username.setOpaque(true);

        jLabel_password.setOpaque(true);

        jTextField_username.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jTextField_username.setForeground(new java.awt.Color(153, 153, 153));
        jTextField_username.setText("USERNAME");
        jTextField_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_usernameActionPerformed(evt);
            }
        });
        jTextField_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_usernameFocusLost(evt);
            }
        });

        jPasswordField.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jPasswordField.setForeground(new java.awt.Color(153, 153, 153));
        jPasswordField.setText("PASSWORD");
        jPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldActionPerformed(evt);
            }
        });
        jPasswordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordFieldFocusLost(evt);
            }
        });

        jButton_login.setBackground(new java.awt.Color(0, 84, 140));
        jButton_login.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        jButton_login.setForeground(new java.awt.Color(204, 204, 204));
        jButton_login.setText("LOGIN");
        jButton_login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_loginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_loginMouseExited(evt);
            }
        });
        jButton_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_loginActionPerformed(evt);
            }
        });

        jLabel_Create_Account.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_Create_Account.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Create_Account.setForeground(new java.awt.Color(255, 102, 102));
        jLabel_Create_Account.setText(">>No Account? Create One!");
        jLabel_Create_Account.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Create_Account.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_Create_AccountMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_Create_AccountMouseEntered(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Create_AccountMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(84, 84, 84))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel_username, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                                    .addComponent(jLabel_password, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(35, 35, 35)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField_username, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
                            .addComponent(jPasswordField)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jLabel_Create_Account)))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_username, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel_username, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel_password, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)))
                .addComponent(jButton_login, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_Create_Account)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        //set icon to the jlabel
        jLabel_username.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/username.png")));
        //set icon to the jlabel
        jLabel_password.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/password.png")));

        jpanel_title.setBackground(new java.awt.Color(51, 153, 0));
        jpanel_title.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LOGIN ");

        javax.swing.GroupLayout jpanel_titleLayout = new javax.swing.GroupLayout(jpanel_title);
        jpanel_title.setLayout(jpanel_titleLayout);
        jpanel_titleLayout.setHorizontalGroup(
            jpanel_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel_titleLayout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(69, 69, 69))
        );
        jpanel_titleLayout.setVerticalGroup(
            jpanel_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel_titleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        javax.swing.GroupLayout labLayout = new javax.swing.GroupLayout(lab);
        lab.setLayout(labLayout);
        labLayout.setHorizontalGroup(
            labLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(labLayout.createSequentialGroup()
                .addContainerGap(207, Short.MAX_VALUE)
                .addComponent(jpanel_title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(jLabel_min, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_close, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(labLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        labLayout.setVerticalGroup(
            labLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(labLayout.createSequentialGroup()
                .addGroup(labLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(labLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(labLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_close)
                            .addComponent(jLabel_min)))
                    .addComponent(jpanel_title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void jLabel_minMouseEntered(java.awt.event.MouseEvent evt) {                                        
        // TODO add your handling code here:
        // edited by kipa
               // create a black border for the close  & minimize jlabels 
          Border label_border = BorderFactory.createMatteBorder(1,1,1,1,Color.white); 
          jLabel_min.setBorder(label_border);
          jLabel_min.setForeground(Color.white);
    }                                       

    private void jLabel_minMouseExited(java.awt.event.MouseEvent evt) {                                       
        // TODO add your handling code here:
               // create a black border for the close  & minimize jlabels 
          Border label_border = BorderFactory.createMatteBorder(1,1,1,1,Color.black); 
          jLabel_min.setBorder(label_border);
          jLabel_min.setForeground(Color.black);
    }                                      

    private void jLabel_closeMouseEntered(java.awt.event.MouseEvent evt) {                                          
  
        // edited by kipa
               // create a black border for the close  & minimize jlabels 
          Border label_border = BorderFactory.createMatteBorder(1,1,1,1,Color.white); 
          jLabel_close.setBorder(label_border);
          jLabel_close.setForeground(Color.white);
    }                                         

    private void jLabel_closeMouseExited(java.awt.event.MouseEvent evt) {                                         
// edited by kipa
           // create a black border for the close  & minimize jlabels 
          Border label_border = BorderFactory.createMatteBorder(1,1,1,1,Color.black); 
          jLabel_close.setBorder(label_border);
          jLabel_close.setForeground(Color.black);
    }                                        

    private void jPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void jTextField_usernameActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // TODO add your handling code here:
    }                                                   

    private void jTextField_usernameFocusGained(java.awt.event.FocusEvent evt) {                                                
      
        //clear the textfeild on focus if the text is "username"
        if(jTextField_username.getText().trim().toLowerCase().equals("username"))
            
        {
        jTextField_username.setText("");
        jTextField_username.setForeground(Color.black);
        
        }
        //set yellow boarder to the jlabel icon
          Border jLabel_icon = BorderFactory.createMatteBorder(0,1,1,1,Color.yellow);
         jLabel_username.setBorder(jLabel_icon);
        
        
        
    }                                               

    private void jTextField_usernameFocusLost(java.awt.event.FocusEvent evt) {                                              
        //if the text field is equals to username or empty
        
        // we will set the "username" text in the field 
        //on focus lost event 
        if (jTextField_username.getText().trim().equals("") ||
        jTextField_username.getText().trim().equalsIgnoreCase("username")) {

        jTextField_username.setText("username");
        jTextField_username.setForeground(new Color(153,153,153));
    }

    Border label_icons_border =
        BorderFactory.createMatteBorder(1,1,1,1, new Color(152,153,153)); 
    jLabel_username.setBorder(label_icons_border);
    }                                             

    private void jPasswordFieldFocusLost(java.awt.event.FocusEvent evt) {                                         
          //if the password field is equals to password or empty
        
        // we will set the "password" text in the field 
        //on focus lost event 
          //get the password text 
        String pass = String.valueOf(jPasswordField.getPassword());

    if (pass.trim().equals("") || pass.equalsIgnoreCase("password")) {
        jPasswordField.setText("password");
        jPasswordField.setForeground(new Color(153,153,153));
    }

    Border label_icons_border =
        BorderFactory.createMatteBorder(1,1,1,1, new Color(152,153,153)); 
    jLabel_password.setBorder(label_icons_border);
    }                                        

    private void jPasswordFieldFocusGained(java.awt.event.FocusEvent evt) {                                           
         
        //clear the password feild on focus if the text is "password"
        //get the password text 
        String pass = String.valueOf(jPasswordField.getPassword());
        if(pass.trim().toLowerCase().equals("password"))
            
        {
        jPasswordField.setText("");
        jPasswordField.setForeground(Color.black);
        
        }
        //set yellow boarder to the jlabel icon
          Border jLabel_icon = BorderFactory.createMatteBorder(0,1,1,1,Color.yellow);
         jLabel_password.setBorder(jLabel_icon);
    }                                          

    private void jButton_loginMouseEntered(java.awt.event.MouseEvent evt) {                                           
          // set jbutton background
        jButton_login.setBackground(new Color (0,101,183));
    }                                          

    private void jButton_loginMouseExited(java.awt.event.MouseEvent evt) {                                          
        // set jbutton background
        jButton_login.setBackground(new Color (0,84,104));
    }                                         

    private void jLabel_minMouseClicked(java.awt.event.MouseEvent evt) {                                        
        // to make the minimize button work
       this.setState(JFrame.ICONIFIED);
    }                                       

    private void jLabel_closeMouseClicked(java.awt.event.MouseEvent evt) {                                          
        // to make the close button work 
       System.exit(0);
    }                                         

    private void jButton_loginActionPerformed(java.awt.event.ActionEvent evt) {                                              
         PreparedStatement st;
    ResultSet rs;

    String username = jTextField_username.getText();
    String password = String.valueOf(jPasswordField.getPassword());

    String query = "SELECT * FROM users WHERE username = ? AND password = ?";

    try {
        st = My_CNX.getConnection().prepareStatement(query);

        st.setString(1, username);
        st.setString(2, password);

        rs = st.executeQuery();

        if (rs.next()) {
            Snake_game form = new Snake_game();
            form.setVisible(true);
            form.pack();
            form.setLocationRelativeTo(null);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(
                null,
                "Invalid Username or Password",
                "Login Error", 2
            );
        }

    } catch (SQLException ex) {
        Logger.getLogger(lOGINFORM.class.getName()).log(Level.SEVERE, null, ex);
    }
    }                                             

    private void jLabel_Create_AccountMouseEntered(java.awt.event.MouseEvent evt) {                                                   
        Border label_border = BorderFactory.createMatteBorder(0,0,1,0,Color.red); 
        jLabel_Create_Account.setBorder(label_border);
    }                                                  

    private void jLabel_Create_AccountMouseExited(java.awt.event.MouseEvent evt) {                                                  
        Border label_Create_Account_border = BorderFactory.createMatteBorder(0,0,1,0,  Color.lightGray); 
          jLabel_Create_Account.setBorder(label_Create_Account_border);
    }                                                 

    private void jLabel_Create_AccountMouseClicked(java.awt.event.MouseEvent evt) {                                                   
        Register_form rf = new Register_form();
        
        rf.setVisible(true);
        rf.pack();
        rf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }                                                  

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lOGINFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lOGINFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lOGINFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lOGINFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lOGINFORM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton_login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_Create_Account;
    private javax.swing.JLabel jLabel_close;
    private javax.swing.JLabel jLabel_min;
    private javax.swing.JLabel jLabel_password;
    private javax.swing.JLabel jLabel_username;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField jTextField_username;
    private javax.swing.JPanel jpanel_title;
    private javax.swing.JPanel lab;
    // End of variables declaration                   
}
// 1.47.15
